apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: charts-helm
  namespace: flux-system
spec:
  interval: 30s
  url: https://kushwahaghub.github.io/flux-sample-charts
  secretRef:
    name: git-credentials