apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-infra-repos
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: http://github.com/kushwahagHub/flux-infra
  secretRef:
    name: git-credentials