apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  chart:
    spec:
      version: "=9.10.3"
  targetNamespace: amazon-cloudwatch
  values:
    autoDiscovery:
      clusterName: docker-desktop
    image:
      tag: v1.21.0