apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-cloudwatch-metrics
  namespace: flux-system
spec:
  chart:
    spec:
      version: "=1.247345"
  targetNamespace: amazon-cloudwatch
  values:
    clusterName: docker-desktop