apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cluster-autoscaler
      version: "=9.10.3"
      sourceRef:
        kind: HelmRepository
        name: charts-helm
        namespace: flux-system
  install: {}
  interval: 30s
  targetNamespace: amazon-cloudwatch
  values:
    autoDiscovery:
      clusterName: cluster.local
    image:
      tag: v1.21.0