apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-cloudwatch-metrics
  namespace: flux-system
spec:
  chart:
    spec:
      chart: aws-cloudwatch-metrics
      sourceRef:
        kind: GitRepository
        name: charts-repo
  install: {}
  interval: 30s
  targetNamespace: amazon-cloudwatch
  values:
    clusterName: cluster.local
