apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: charts-helm
  namespace: flux-system
spec:
  interval: 30s
  url: https://kushwahaghub.github.io/flux-sample-charts
  secretRef:
    name: git-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 15m
  path: "./apps/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-infra-repos
  timeout: 5m
