apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 5m
  path: ./flux-infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-infra-repos
